version: 1.0.{build}
build:
  project: Panda Obfuscator.sln
  verbosity: minimal
install:
  # by default, all script lines are interpreted as batch
  - git submodule update --init --recursive
after_build:
  - 7z a Panda.zip Debug\bin\*
artifacts:
  - path: Panda.zip
    name: Panda
